### ISSUE TITLE
Access to polkadot-hackathon-apac

### ISSUE THREAD

**Issue by jimmychu0807** [Doordashcon/rust-server-react-client#1]
Hi, I just saw the invite to the `Doordashcon/polkadot-hackathon-apac`, but it has been expired. Could you invite me (@jimmychu0807) and @uosvald in the repo again? Thanks

**Comment by Doordashcon** [comment]
Will do so again, thank you for notifying me

**Comment by Doordashcon** [comment]
opting out of pathways, learnt a lot thanks
